In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import statsmodels.api as sm
from sklearn import linear_model as lm

In [2]:
x_1 = np.random.uniform(10,40,100)
x_2 = np.random.uniform(-50,20,100)
x_3 = np.random.uniform(20,60,100)
x_4 = np.random.uniform(10,40,100)
x_5 = np.random.uniform(-50,20,100)
x_6 = np.random.uniform(20,60,100)
epsilon = np.random.normal(0,10,100)

In [3]:
y=-30+1.3*x_1+1.6*x_2+1.1*x_3+0.7*x_4-2.1*x_5-0.9*x_6+epsilon

In [4]:
X_ols=pd.DataFrame()
X_ols['Constant']=pd.Series(np.ones(100))
X_ols['X1'] = pd.Series(x_1)
X_ols['X2'] = pd.Series(x_2)
X_ols['X3'] = pd.Series(x_3)
X_ols['X4'] = pd.Series(x_4)
X_ols['X5'] = pd.Series(x_5)
X_ols['X6'] = pd.Series(x_6)

In [5]:
model_reg = sm.OLS(y,X_ols).fit()
model_reg.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.973
Model:                            OLS   Adj. R-squared:                  0.972
Method:                 Least Squares   F-statistic:                     563.6
Date:                Mon, 30 Sep 2024   Prob (F-statistic):           8.36e-71
Time:                        12:40:06   Log-Likelihood:                -373.41
No. Observations:                 100   AIC:                             760.8
Df Residuals:                      93   BIC:                             779.1
Df Model:                           6                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Constant     -32.6721      7.525     -4.342      0.000     -47.615     -17.729
X1             1.3130      0.122     10.760      0.000       1.071       1.555
X2             1.7141      0.056     30.739      0.000       1.603       1.825
X3             0.9616      0.093     10.307      0.000       0.776       1.147
X4             0.6806      0.129      5.266      0.000       0.424       0.937
X5            -2.1590      0.053    -40.576      0.000      -2.265      -2.053
X6            -0.7238      0.099     -7.288      0.000      -0.921      -0.527
==============================================================================
Omnibus:                        0.320   Durbin-Watson:                   1.622
Prob(Omnibus):                  0.852   Jarque-Bera (JB):                0.122
Skew:                          -0.081   Prob(JB):                        0.941
Kurtosis:                       3.058   Cond. No.                         515.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [6]:
# Now we add some unrelated coefficients
x_7 = np.random.uniform(10,40,100)
x_8 = np.random.uniform(-50,20,100)
x_9 = np.random.uniform(20,60,100)
x_10 = np.random.uniform(10,40,100)
x_11 = np.random.uniform(-50,20,100)
x_12 = np.random.uniform(20,60,100)

In [7]:
X_ext = pd.DataFrame()
X_ext['Constant']=pd.Series(np.ones(100))
X_ext['X1'] = pd.Series(x_1)
X_ext['X2'] = pd.Series(x_2)
X_ext['X3'] = pd.Series(x_3)
X_ext['X4'] = pd.Series(x_4)
X_ext['X5'] = pd.Series(x_5)
X_ext['X6'] = pd.Series(x_6)
X_ext['X7'] = pd.Series(x_7)
X_ext['X8'] = pd.Series(x_8)
X_ext['X9'] = pd.Series(x_9)
X_ext['X10'] = pd.Series(x_10)
X_ext['X11'] = pd.Series(x_11)
X_ext['X12'] = pd.Series(x_12)

In [8]:
model_reg = sm.OLS(y,X_ext).fit()
model_reg.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.975
Model:                            OLS   Adj. R-squared:                  0.972
Method:                 Least Squares   F-statistic:                     285.1
Date:                Mon, 30 Sep 2024   Prob (F-statistic):           2.32e-64
Time:                        12:40:06   Log-Likelihood:                -369.60
No. Observations:                 100   AIC:                             765.2
Df Residuals:                      87   BIC:                             799.1
Df Model:                          12                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Constant     -14.3536     10.924     -1.314      0.192     -36.067       7.359
X1             1.2764      0.125     10.229      0.000       1.028       1.524
X2             1.6966      0.056     30.110      0.000       1.585       1.809
X3             0.9205      0.095      9.679      0.000       0.731       1.110
X4             0.6069      0.137      4.421      0.000       0.334       0.880
X5            -2.1395      0.055    -38.989      0.000      -2.249      -2.030
X6            -0.7422      0.100     -7.396      0.000      -0.942      -0.543
X7            -0.0938      0.135     -0.694      0.490      -0.362       0.175
X8            -0.0232      0.053     -0.437      0.663      -0.129       0.082
X9            -0.1420      0.093     -1.527      0.130      -0.327       0.043
X10            0.0098      0.126      0.078      0.938      -0.241       0.261
X11            0.0512      0.058      0.882      0.380      -0.064       0.167
X12           -0.1332      0.092     -1.442      0.153      -0.317       0.050
==============================================================================
Omnibus:                        0.600   Durbin-Watson:                   1.700
Prob(Omnibus):                  0.741   Jarque-Bera (JB):                0.382
Skew:                          -0.149   Prob(JB):                        0.826
Kurtosis:                       3.049   Cond. No.                     1.05e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.05e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [9]:
# When we input the matrix, we don't need to add the column of ones because \
# Lasso automatically takes it into account

X_ext = X_ext.drop(columns=['Constant'])
model_lasso = lm.Lasso(alpha=1).fit(X_ext,y)
model_lasso.coef_

array([ 1.26370476,  1.69677833,  0.91024211,  0.58758196, -2.13864493,
       -0.73417723, -0.07855273, -0.02265897, -0.13914921,  0.        ,
        0.0505828 , -0.13011214])

In [10]:
model_lasso = lm.Lasso(alpha=10).fit(X_ext,y)
model_lasso.coef_

array([ 1.14973217,  1.69924372,  0.81150393,  0.4300906 , -2.13010932,
       -0.66266055, -0.        , -0.02167832, -0.10376503, -0.        ,
        0.04472617, -0.09614228])

In [11]:
# We now apply Ridge Regression to our data

model_ridge = lm.Ridge(alpha=10).fit(X_ext,y)
model_ridge.coef_

array([ 1.27464241,  1.69625134,  0.91940855,  0.60541907, -2.13895268,
       -0.74188045, -0.0937838 , -0.02337289, -0.14237055,  0.0096495 ,
        0.05150843, -0.1332167 ])

In [12]:
model_ridge = lm.Ridge(alpha=10000).fit(X_ext,y)
model_ridge.coef_

array([ 0.57570239,  1.38202373,  0.4455731 ,  0.17349253, -1.72103565,
       -0.53363709, -0.11065111, -0.09111359, -0.23608019, -0.02907018,
        0.16976035, -0.07961734])